#pragma once

#include "CoreMinimal.h"
#include "Definitions.h"
#include "Blueprint/UserWidget.h"
#include "Components/TextBlock.h"
#include "Items/InventoryItemBase.h"
#include "UI/InventoryBagWindowInterface.h"
#include "BagWidget.generated.h"

class UInventoryGridWidget;

/**
 * Plugin default bag widget.
 *
 * Implements IInventoryBagWindowInterface so it can be registered in and driven by
 * IInventoryHUDInterface's C++ bag lifecycle defaults.
 *
 * Required Blueprint binding:
 *   - "InventoryGrid"  (UInventoryGridWidget, mandatory)
 * Optional Blueprint binding:
 *   - "BagNameText"    (UTextBlock, optional)
 */
UCLASS()
class INVENTORYPLUGIN_API UBagWidget : public UUserWidget, public IInventoryBagWindowInterface
{
	GENERATED_BODY()

protected:
	UPROPERTY(BlueprintReadWrite, Category = "Inventory|Bag")
	FString BagName;

	UPROPERTY(BlueprintReadWrite, Category = "Inventory|Bag")
	int32 BagWidth = 0;

	UPROPERTY(BlueprintReadWrite, Category = "Inventory|Bag")
	int32 BagHeight = 0;

	UPROPERTY(BlueprintReadWrite, Category = "Inventory|Bag")
	EItemSize BagSize = EItemSize::Giant;

	UPROPERTY(BlueprintReadWrite, Category = "Inventory|Bag")
	EBagSlot CurrentBagSlot = EBagSlot::Unknown;

	UPROPERTY(BlueprintReadWrite, Category = "Inventory|Bag")
	UUserWidget* ParentWidget = nullptr;

	UPROPERTY(BlueprintReadWrite, meta = (BindWidget), Category = "Inventory|Bag")
	UInventoryGridWidget* InventoryGrid = nullptr;

	/** Optional text block to display the bag name. */
	UPROPERTY(BlueprintReadWrite, meta = (BindWidgetOptional), Category = "Inventory|Bag|UI")
	UTextBlock* BagNameText = nullptr;

public:
	// ---- IInventoryBagWindowInterface ----------------------------------------
	// InitBagData and InitUI UFUNCTION declarations are generated by UHT from the
	// interface; only _Implementation overrides are declared here.

	virtual void InitBagData_Implementation(const FString& InBagName, int32 InBagWidth,
	                                         int32 InBagHeight, EItemSize InBagSize,
	                                         EBagSlot InBagSlot) override;
	virtual void InitUI_Implementation() override;
	virtual void RefreshBagWindow_Implementation() override;
	virtual void ShowBagWindow_Implementation() override;
	virtual void HideBagWindow_Implementation() override;
	virtual void ToggleBagWindow_Implementation() override;
	virtual void DeInitBagWindow_Implementation() override;
	virtual void LockBagItemSlot_Implementation(int32 TopLeft, bool bLocked) override;

	// ---- Legacy direct API (kept for backward compatibility) ------------------
	// These delegate to the interface methods above so both call paths remain valid.

	/**
	 * Refreshes the bag grid. C++ default calls InventoryGrid->Refresh().
	 * Blueprint may override to add visual feedback.
	 */
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, BlueprintCosmetic)
	void Refresh();
	virtual void Refresh_Implementation();

	UFUNCTION(BlueprintCallable, BlueprintCosmetic)
	void Hide();

	UFUNCTION(BlueprintCallable, BlueprintCosmetic)
	void Show();

	UFUNCTION(BlueprintCallable, BlueprintCosmetic)
	void ToggleDisplay();

	/**
	 * Cleans up the bag grid. C++ default calls InventoryGrid->DeInitData().
	 * Blueprint may override to handle close animations.
	 */
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, BlueprintCosmetic)
	void DeInitBagData();
	virtual void DeInitBagData_Implementation();

	/**
	 * Lock or unlock a specific item slot in this bag.
	 * @param TopLeft The top-left index of the item in the bag grid.
	 * @param bLocked True to lock, false to unlock.
	 */
	UFUNCTION(BlueprintCallable, BlueprintNativeEvent, BlueprintCosmetic, Category = "Inventory")
	void LockItemSlot(int32 TopLeft, bool bLocked);
	virtual void LockItemSlot_Implementation(int32 TopLeft, bool bLocked);
};
